# Site settings
title: Mobile Pattern Library
email: andy@freeagent.com
description: "Fuck yeh! Pattern library"
baseurl: "/patterns/"
url: "http://andyirvine.github.io/patterns/"

# Build settings

name: Patterns
markdown: redcarpet
highlighter: true
baseurl: /patterns
